### PR TITLE
Add second trailer monarch  legacy of monsters

### PR DESCRIPTION
**Pull request by devNenyasha**

### CODE REVIEW

**Comment by devNenyasha** [comment]
@mitchiemt11 Please review this PR when you have a chance."

**Comment by mitchiemt11** [comment]
@devNenyasha please resolve conflicts.

**Review by mitchiemt11 — CHANGES_REQUESTED** [review]
we should not have 3 tiger data in this commit.

**Comment by devNenyasha** [comment]
connflicts solved

**Review by mitchiemt11 — APPROVED** [review]

**Pull request merged**
